# See:
#   https://docs.helix-editor.com/master/languages.html
#   https://github.com/helix-editor/helix/blob/master/languages.toml


# rust
[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"


# cpp
[[language]]
name = "cpp"
language-servers = [ "clangd" ]


# golang
[[language]]
name = "go"
auto-format = false
language-servers = [ "gopls" ]

[language-server.gopls]
command = "gopls"
